# Generated by Django 5.0.3 on 2024-03-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("image_caption_app", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ImageCaption",
        ),
        migrations.RemoveField(
            model_name="image",
            name="image",
        ),
        migrations.AddField(
            model_name="image",
            name="caption",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="image",
            name="file",
            field=models.ImageField(default=" ", upload_to="uploads/"),
            preserve_default=False,
        ),
    ]
